// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_a5sP9r7klwP-tcL252zo7g3yL3Wj258',
    appId: '1:463614582361:web:2704deedc2f08d4da59b48',
    messagingSenderId: '463614582361',
    projectId: 'cosine-13a7b',
    authDomain: 'cosine-13a7b.firebaseapp.com',
    storageBucket: 'cosine-13a7b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhVce8v2baKx6uIEBkXNqoZ-VPf9yvD5k',
    appId: '1:463614582361:android:2fcc5abbde43239da59b48',
    messagingSenderId: '463614582361',
    projectId: 'cosine-13a7b',
    storageBucket: 'cosine-13a7b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBe5RFoccfEmhfMUhnxuYkMuBbNenAQNm8',
    appId: '1:463614582361:ios:734415cc7c98b64fa59b48',
    messagingSenderId: '463614582361',
    projectId: 'cosine-13a7b',
    storageBucket: 'cosine-13a7b.appspot.com',
    iosBundleId: 'com.example.cosine',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBe5RFoccfEmhfMUhnxuYkMuBbNenAQNm8',
    appId: '1:463614582361:ios:734415cc7c98b64fa59b48',
    messagingSenderId: '463614582361',
    projectId: 'cosine-13a7b',
    storageBucket: 'cosine-13a7b.appspot.com',
    iosBundleId: 'com.example.cosine',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_a5sP9r7klwP-tcL252zo7g3yL3Wj258',
    appId: '1:463614582361:web:6776f77f977c6734a59b48',
    messagingSenderId: '463614582361',
    projectId: 'cosine-13a7b',
    authDomain: 'cosine-13a7b.firebaseapp.com',
    storageBucket: 'cosine-13a7b.appspot.com',
  );
}
